name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: nasm
        execute_install_scripts: true
    - name: make
      run: |
        cd free95
        make all
    - uses: actions/upload-artifact@v4
      with:
        name: Kernel
        path: free95/build/bin/
